theme: jekyll-theme-cayman

social:
  - title: email
    url: mailto: raviteja.research@gmail.com
  - title: twitter
    url: https://twitter.com/ravitejanaraya?s=09
  - title: linkedin
    url: https://www.linkedin.com/in/raviteja-tirumalapudi-6a7082174/
